services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    env_file:
      -  ./backend/.env
    volumes:
      - ./backend:/home/node/app
      - /home/node/app/node_modules
      - /Users/jacob/.google-credentials/:/run/secrets:ro
    command: npx nodemon --exec "npx ts-node src/server.ts"
    environment:
      - CHOKIDAR_USEPOLLING=true

  web:
    build:
      context: ./web
    ports:
      - "3000:3000"
    env_file:
      - ./web/.env.local
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3001
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./web:/home/node/app
      - /home/node/app/node_modules
    command: npm run dev
    depends_on:
      - backend


      